apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polybot-dev
  name: polybot-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
        - image: yazanyehya/polybot-dev:72
          name: polybot-container
          env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-token
                key: token
          - name: S3_BUCKET_NAME
            value: yazan-polybot-images-dev
          - name: QUEUE_URL
            value: yazan_sqs_dev
          - name: NGINX_URL
            value: https://yazanpolybot-dev.fursa.click